name: fossa
on:
  pull_request:
  push:
    branches:
      - 'main'
jobs:
  fossa-scan:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: fossas/fossa-action@main
        with:
          api-key: ${{secrets.FOSSA_API_KEY}}
